// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Testing.DataModels;

namespace Testing.DataModels.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    [Migration("20201119130549_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Testing.DataModels.Student", b =>
                {
                    b.Property<int>("StudentNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.HasKey("StudentNumber");

                    b.ToTable("Students");

                    b.HasData(
                        new { StudentNumber = 1, EmailAddress = "viktorijajovanovska@gmail.com", FullName = "Viktorija Jovanovska", Id = 0, PhoneNumber = "+38970123456" }
                    );
                });

            modelBuilder.Entity("Testing.DataModels.Subject", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Credits");

                    b.Property<int>("Semestar");

                    b.Property<int>("StudentId");

                    b.HasKey("Name");

                    b.HasIndex("StudentId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new { Name = "History", Credits = 3, Semestar = 2, StudentId = 1 },
                        new { Name = "Chemistry", Credits = 2, Semestar = 2, StudentId = 1 },
                        new { Name = "English", Credits = 2, Semestar = 2, StudentId = 1 },
                        new { Name = "French", Credits = 2, Semestar = 2, StudentId = 1 }
                    );
                });

            modelBuilder.Entity("Testing.DataModels.Subject", b =>
                {
                    b.HasOne("Testing.DataModels.Student", "Student1")
                        .WithMany("Subjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
